export const LOGIN_ACTION = 'LOGIN_ACTION'

export const LOGOUT_ACTION = 'LOGOUT_ACTION'

export const LOGIN_GG_ACTION = 'LOGIN_GG_ACTION'

export const ADD_TO_MYBOOK_ACTION = 'ADD_TO_MYBOOK_ACTION'

export const REMOVE_FROM_MYBOOK_ACTION = 'REMOVE_FROM_MYBOOK_ACTION'


